container:
  nix-build --expr 'with import <nixpkgs>{}; (pkgs.callPackage ./default.nix {}).container'
  docker load < ./result

pkg:
  nix-build --expr 'with import <nixpkgs>{}; (pkgs.callPackage ./default.nix {}).knot'

inspect:
  dive andrewzah/knot:0.11.0-unstable-26-1-25
